spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
server:
  port: 8888